definitions:
  config:
    /hippo:configuration/hippo:queries/hippo:templates/new-blog-folder:
      jcr:primaryType: hippostd:templatequery
      jcr:mixinTypes: ['hipposys:implementation']
      hippostd:icon: addfolder_ico
      hippostd:modify: [./_name, $name, './hippotranslation:id', $uuid, './hippotranslation:locale',
        $inherited]
      hipposys:classname: org.hippoecm.repository.impl.query.DirectPath
      jcr:language: xpath
      jcr:statement: /jcr:root/hippo:configuration/hippo:queries/hippo:templates/new-blog-folder/hippostd:templates/node()
      /hippostd:templates:
        jcr:primaryType: hippostd:templates
        /hippostd:folder:
          jcr:primaryType: hippostd:folder
          jcr:mixinTypes: ['hippotranslation:translated', 'mix:referenceable']
          jcr:uuid: 3772affa-db4e-4048-8da0-77eea2dff0d4
          hippostd:foldertype: [new-blog-document, new-blog-folder]
          hippotranslation:id: generated id
          hippotranslation:locale: inherited locale
