definitions:
  config:
    /hippo:namespaces/contenteximdemo/account:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: e4b0343f-c5a9-4d85-864a-a49ab6a5a56a
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 7c6a6532-bb07-42c0-9b3e-06e1a406eb03
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel', 'mix:referenceable']
          jcr:uuid: bf886c8a-34e9-4ad9-affb-3f8cb91fe2f6
          hipposysedit:node: true
          hipposysedit:supertype: ['hippo:compound', 'hippostd:relaxed']
          hipposysedit:uri: http://www.onehippo.org/contenteximdemo/nt/1.0
          /type:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: contenteximdemo:type
            hipposysedit:primary: false
            hipposysedit:type: DynamicDropdown
            hipposysedit:validators: [non-empty, required]
          /link:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: contenteximdemo:link
            hipposysedit:primary: false
            hipposysedit:type: String
            hipposysedit:validators: [non-empty, required]
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: contenteximdemo:account
          contenteximdemo:link: ''
          contenteximdemo:type: ''
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          type: contenteximdemo:account
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /type:
            jcr:primaryType: frontend:plugin
            caption: Type
            field: type
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              source: /content/documents/contenteximdemo/blog/account-types
          /link:
            jcr:primaryType: frontend:plugin
            field: link
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
