definitions:
  config:
    /hippo:namespaces/contenteximdemo/blogpost:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: 475bfc5a-899b-4f7e-9dda-dec8c5fdb302
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 50697c7f-9243-4f15-88fb-ac07c1b91712
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel', 'mix:referenceable']
          jcr:uuid: 5114c2db-a91d-41f3-a0e7-06c83d035966
          hipposysedit:node: true
          hipposysedit:supertype: ['contenteximdemo:basedocument', 'hippostd:relaxed',
            'hippotranslation:translated']
          hipposysedit:uri: http://www.onehippo.org/contenteximdemo/nt/1.0
          /publicationdate:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: contenteximdemo:publicationdate
            hipposysedit:primary: false
            hipposysedit:type: Date
            hipposysedit:validators: [required]
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: contenteximdemo:title
            hipposysedit:primary: false
            hipposysedit:type: String
            hipposysedit:validators: [non-empty, required]
          /introduction:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: contenteximdemo:introduction
            hipposysedit:primary: false
            hipposysedit:type: Text
          /content:
            jcr:primaryType: hipposysedit:field
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: contenteximdemo:content
            hipposysedit:primary: false
            hipposysedit:type: hippostd:html
          /categories:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: true
            hipposysedit:ordered: false
            hipposysedit:path: contenteximdemo:categories
            hipposysedit:primary: false
            hipposysedit:type: DynamicDropdown
          /authors:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: contenteximdemo:authors
            hipposysedit:primary: false
            hipposysedit:type: hippo:mirror
            hipposysedit:validators: [required]
          /authornames:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: contenteximdemo:authornames
            hipposysedit:primary: false
            hipposysedit:type: String
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 40c09472-315f-4ad1-b283-c70ced0fbc73
        /hipposysedit:prototype:
          jcr:primaryType: contenteximdemo:blogpost
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: a8b5a337-dc65-4ab3-b67a-b16690013a1f
          contenteximdemo:authornames: ['']
          contenteximdemo:introduction: ''
          contenteximdemo:publicationdate: 0001-01-01T13:00:00+01:00
          contenteximdemo:title: ''
          hippo:related___pathreference: blogpost/hipposysedit:prototypes
          hippostd:state: unpublished
          hippostdpubwf:createdBy: ''
          hippostdpubwf:creationDate: 2014-03-06T15:13:00+01:00
          hippostdpubwf:lastModificationDate: 2014-03-06T15:13:00+01:00
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          /contenteximdemo:content:
            jcr:primaryType: hippostd:html
            hippostd:content: ''
          /contenteximdemo:authors:
            jcr:primaryType: hippo:mirror
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [engine, wicket.model, model.compareTo, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            extension.left: ${cluster.id}.left
            extension.right: ${cluster.id}.right
            plugin.class: org.hippoecm.frontend.editor.layout.TwoColumn
            wicket.extensions: [extension.left, extension.right]
            wicket.id: ${wicket.id}
          /left:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.left.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.left
          /right:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.right.item
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
            wicket.id: ${cluster.id}.right
          /authors:
            jcr:primaryType: frontend:plugin
            field: authors
            hint: authors.hint
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              nodetypes: contenteximdemo:author
          /publicationdate:
            jcr:primaryType: frontend:plugin
            field: publicationdate
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /title:
            jcr:primaryType: frontend:plugin
            field: title
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /introduction:
            jcr:primaryType: frontend:plugin
            field: introduction
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /content:
            jcr:primaryType: frontend:plugin
            field: content
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /categories:
            jcr:primaryType: frontend:plugin
            caption: Categories
            field: categories
            multiselect.type: selectlist
            plugin.class: org.onehippo.forge.selection.frontend.plugin.DynamicMultiSelectPlugin
            selectlist.maxrows: '8'
            valuelist.provider: service.valuelist.default
            wicket.id: ${cluster.id}.right.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              source: /content/documents/contenteximdemo/blog/blog-categories
          /taggable:
            jcr:primaryType: frontend:plugin
            mixin: hippostd:taggable
            plugin.class: org.hippoecm.frontend.editor.plugins.mixin.MixinLoaderPlugin
            wicket.id: ${cluster.id}.left.item
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
