definitions:
  config:
    /hippo:namespaces/contenteximdemo/faqlist:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      jcr:uuid: f0bb9f97-e6a5-4ce2-8169-55b292e8fb98
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: a27cd4e7-dc78-478c-91c4-1cbb965d50a1
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel', 'mix:referenceable']
          jcr:uuid: 6355f6b4-e7cc-4c82-ab3b-e914c4269b7c
          hipposysedit:node: true
          hipposysedit:supertype: ['contenteximdemo:basedocument', 'hippostd:relaxed',
            'hippotranslation:translated']
          hipposysedit:uri: http://www.onehippo.org/contenteximdemo/nt/1.0
          /title:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: contenteximdemo:title
            hipposysedit:primary: false
            hipposysedit:type: String
            hipposysedit:validators: [non-empty, required]
          /description:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: contenteximdemo:description
            hipposysedit:primary: false
            hipposysedit:type: hippostd:html
          /faqitem:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: true
            hipposysedit:ordered: true
            hipposysedit:path: contenteximdemo:faqitem
            hipposysedit:primary: false
            hipposysedit:type: hippo:mirror
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: contenteximdemo:faqlist
          jcr:mixinTypes: ['mix:referenceable']
          jcr:uuid: 2ca91061-d470-408b-8f4e-1d190477ffd4
          contenteximdemo:title: ''
          hippo:related___pathreference:
            type: double
            value: []
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:creationDate: 2014-06-20T11:16:58.810+02:00
          hippostdpubwf:lastModificationDate: 2014-06-20T11:16:58.810+02:00
          hippostdpubwf:lastModifiedBy: ''
          hippotranslation:id: document-type-locale-id
          hippotranslation:locale: document-type-locale
          /contenteximdemo:description:
            jcr:primaryType: hippostd:html
            hippostd:content: ''
          /contenteximdemo:faqitem:
            jcr:primaryType: hippo:mirror
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /title:
            jcr:primaryType: frontend:plugin
            field: title
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /description:
            jcr:primaryType: frontend:plugin
            field: description
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /faqitem:
            jcr:primaryType: frontend:plugin
            field: faqitem
            plugin.class: org.hippoecm.frontend.editor.plugins.field.NodeFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
