definitions:
  config:
    /hippo:namespaces/contenteximdemo/basedocument:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 0c5b25ec-7288-45c4-a5c0-2a6e736d15c8
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        jcr:uuid: 2c956918-6a45-43c1-a9d6-ebf846df54a0
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['hipposysedit:remodel']
          hipposysedit:supertype: ['hippo:document', 'hippostdpubwf:document', 'hippostd:publishableSummary']
          hipposysedit:uri: http://www.onehippo.org/contenteximdemo/nt/1.0
