definitions:
  config:
    /hippo:configuration/hippo:update/hippo:registry/Example_Clean_Hippo_Mirror_Docbase_Values_Having_Paths:
      jcr:primaryType: hipposys:updaterinfo
      hipposys:batchsize: 100
      hipposys:description: 'A example script to clean interim hippo:docbase values of Hippo Mirror nodes having paths instead of UUIDs.'
      hipposys:dryrun: false
      hipposys:parameters: '{}'
      hipposys:query: "//element(*)[jcr:like(@hippo:docbase,'/content/%')]"
      hipposys:script:
        type: string
        resource: /configuration/update/registry/example-clean-docbase-values-having-paths
      hipposys:throttle: 10
