definitions:
  config:
    /Example - Clean Hippo Mirror Docbase Values Having Paths:
      jcr:primaryType: hipposys:updaterinfo
      hipposys:batchsize: 10
      hipposys:description: A example script to clean interim hippo:docbase values of
        Hippo Mirror nodes having paths instead of UUIDs.
      hipposys:dryrun: false
      hipposys:parameters: ''
      hipposys:query: //element(*)[jcr:like(@hippo:docbase,'/content/%')]
      hipposys:script: |-
        package org.hippoecm.frontend.plugins.cms.admin.updater

        import java.io.*
        import javax.jcr.*
        import org.apache.commons.lang.*
        import org.onehippo.repository.update.BaseNodeUpdateVisitor

        class CleaningDocbasesHavingPathsUpdateVisitor extends BaseNodeUpdateVisitor {

          boolean doUpdate(Node node) {
            log.debug "Visiting ${node.path}"
            def docbasePath = node.getProperty("hippo:docbase").getString()
            def docbase

            if (StringUtils.startsWith(docbasePath, "/") && node.session.nodeExists(docbasePath)) {
              docbase = node.session.getNode(docbasePath).getIdentifier()
              node.setProperty("hippo:docbase", docbase)
              log.info "Reset ${node.path}/hippo:docbase to '${docbase}' from '${docbasePath}'."
              return true
            }

            return false

          }

          boolean undoUpdate(Node node) {
            throw new UnsupportedOperationException('Updater does not implement undoUpdate method')
          }

          void destroy() {
          }

        }
      hipposys:throttle: 1000
