definitions:
  config:
    /hst:hst/hst:configurations/contenteximdemo/hst:workspace/hst:channel:
      jcr:primaryType: hst:channel
      hst:name: Hippo Content Export / Import Demo
      hst:type: website
      /hst:channelinfo:
        jcr:primaryType: hst:channelinfo
